//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IlmRosPkg
{
    [Serializable]
    public class ColorArrayMsg : Message
    {
        public const string k_RosMessageName = "ilm_ros_pkg/ColorArray";
        public override string RosMessageName => k_RosMessageName;

        public ColorMsg[] colors;
        public bool[] valid;

        public ColorArrayMsg()
        {
            this.colors = new ColorMsg[0];
            this.valid = new bool[0];
        }

        public ColorArrayMsg(ColorMsg[] colors, bool[] valid)
        {
            this.colors = colors;
            this.valid = valid;
        }

        public static ColorArrayMsg Deserialize(MessageDeserializer deserializer) => new ColorArrayMsg(deserializer);

        private ColorArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.colors, ColorMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.valid, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.colors);
            serializer.Write(this.colors);
            serializer.WriteLength(this.valid);
            serializer.Write(this.valid);
        }

        public override string ToString()
        {
            return "ColorArrayMsg: " +
            "\ncolors: " + System.String.Join(", ", colors.ToList()) +
            "\nvalid: " + System.String.Join(", ", valid.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
