//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IlmRosPkg
{
    [Serializable]
    public class ColoredPointcloudMsg : Message
    {
        public const string k_RosMessageName = "ilm_ros_pkg/ColoredPointcloud";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.PointCloud2Msg pointCloud;
        public ColorArrayMsg colorscam1;
        public ColorArrayMsg colorscam2;

        public ColoredPointcloudMsg()
        {
            this.pointCloud = new Sensor.PointCloud2Msg();
            this.colorscam1 = new ColorArrayMsg();
            this.colorscam2 = new ColorArrayMsg();
        }

        public ColoredPointcloudMsg(Sensor.PointCloud2Msg pointCloud, ColorArrayMsg colorscam1, ColorArrayMsg colorscam2)
        {
            this.pointCloud = pointCloud;
            this.colorscam1 = colorscam1;
            this.colorscam2 = colorscam2;
        }

        public static ColoredPointcloudMsg Deserialize(MessageDeserializer deserializer) => new ColoredPointcloudMsg(deserializer);

        private ColoredPointcloudMsg(MessageDeserializer deserializer)
        {
            this.pointCloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
            this.colorscam1 = ColorArrayMsg.Deserialize(deserializer);
            this.colorscam2 = ColorArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pointCloud);
            serializer.Write(this.colorscam1);
            serializer.Write(this.colorscam2);
        }

        public override string ToString()
        {
            return "ColoredPointcloudMsg: " +
            "\npointCloud: " + pointCloud.ToString() +
            "\ncolorscam1: " + colorscam1.ToString() +
            "\ncolorscam2: " + colorscam2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
