//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IlmRosPkg
{
    [Serializable]
    public class ColorMsg : Message
    {
        public const string k_RosMessageName = "ilm_ros_pkg/Color";
        public override string RosMessageName => k_RosMessageName;

        public byte red;
        public byte green;
        public byte blue;

        public ColorMsg()
        {
            this.red = 0;
            this.green = 0;
            this.blue = 0;
        }

        public ColorMsg(byte red, byte green, byte blue)
        {
            this.red = red;
            this.green = green;
            this.blue = blue;
        }

        public static ColorMsg Deserialize(MessageDeserializer deserializer) => new ColorMsg(deserializer);

        private ColorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.red);
            deserializer.Read(out this.green);
            deserializer.Read(out this.blue);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.red);
            serializer.Write(this.green);
            serializer.Write(this.blue);
        }

        public override string ToString()
        {
            return "ColorMsg: " +
            "\nred: " + red.ToString() +
            "\ngreen: " + green.ToString() +
            "\nblue: " + blue.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
